import type { Metadata } from "next";
import { ThemeProvider } from "../components/ui/theme-provider";
import "./globals.css";
import Navbar from "../components/navbar";
import { AppProvider } from "../context/AppContext";
import { SidebarProvider } from "@/components/ui/sidebar";

export const metadata: Metadata = {
  title: "InkNest",
  description: "Generated by create next app",
  icons: {
    icon: "/logo1.png", // Emptying this array disables the default favicon
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
        <AppProvider>
            <Navbar/>
            <SidebarProvider>
              {children}
            </SidebarProvider>
        </AppProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}